all:
   .general:
       salt: mySecret$alt
       yearRangeMin: 1800
       yearRangeMax: <?php echo date('Y')+2; ?>

       dateUpperBound: '2038/12/31'
       dateLowerBound: '0001/01/01'
       yearUpperBound: '2038'
       recPerPage: 10
       pagerSlidingSize: 5
       catalogueRecLimit: 200
# dev:
#    tracking:
#        enabled: true
#        trackfields: true