default:
  http_metas:
    content-type: text/html

  metas:
    title:        Darwin 2
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [reset.css, main.css, superfish.css, menu.css, jquery-ui-1.7.2.custom.css, ui.datepicker.css]

  javascripts:    [jquery-1.3.2.min.js, jquery.ui.all.min.js, core.js, jquery.bgiframe.pack.js, superfish.js, supersubs.js, menu.js, jquery.qtip-1.0.0-rc3.min.js]

  has_layout:     on
  layout:         layout
