default:
  http_metas:
    content-type: text/html

  metas:
    title:        Darwin 2
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [reset.css, main.css, superfish.css, menu.css, jquery-ui-1.7.2.search.css, ui.datepicker.css, jquery.autocomplete.css]

  javascripts:    [jquery-1.3.2.min.js, jquery.ui.all.min.js, jquery-datepicker-fr.js, jquery-datepicker-en.js, jquery-datepicker-nl.js, core.js, jquery.bgiframe.pack.js, superfish.js, supersubs.js, menu.js, jquery.qtip-1.0.0-rc3.min.js, jquery.autocomplete.min.js]

  has_layout:     true
  layout:         layout

editSuccess:
  stylesheets: [jquery-ui-1.7.2.edit.css]
newSuccess:
  stylesheets: [jquery-ui-1.7.2.edit.css]
