default:
  http_metas:
    content-type: text/html

  metas:
    title:        Darwin 2
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [reset.css, main.css, menu.css]

  javascripts:    [jquery-1.4.3.min.js, jquery.ui.all.min.js, core.js, jquery.hoverIntent.minified.js, superfish.js, supersubs.js, jquery.qtip-1.0.0-rc3.min.js, catalogue.js]

  has_layout:     true
  layout:         layout

editSuccess:
  stylesheets: [encod.css]
newSuccess:
  stylesheets: [encod.css]
