all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'pgsql:host=127.0.0.1;dbname=darwin2'
      username: cebmpad
      password: cebmpad
dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'pgsql:host=127.0.0.1;dbname=darwin2'
      username: cebmpad
      password: cebmpad

test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      quote_identifier: true
      dsn: 'pgsql:host=127.0.0.1;dbname=darwin2'
      username: cebmpad
      password: cebmpad

preprod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'pgsql:host=127.0.0.1;dbname=darwin2'
      username: cebmpad
      password: cebmpad
