all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'pgsql:host=127.0.0.1;dbname=darwin2'
      username: cebmpad
      password: cebmpad
dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'pgsql:host=127.0.0.1;dbname=darwin2'
      username: unit
      password: unit

test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      quote_identifier: true
      dsn: 'pgsql:host=127.0.0.1;dbname=darwin2'
      username: unit
      password: unit

preprod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'pgsql:host=127.0.0.1;dbname=darwin2'
      username: darwin2
      password: Cave66
