indexSuccess:
  stylesheets: [widgets.css,specimensearch.css]
  javascripts: [jquery.ui.all.min.js, widgets.js, catalogue.js, specimensearch.js]
  
searchResultSuccess:
  stylesheets: [specimensearch.css]
  javascripts: [specimensearch.js, searchForm.js]

