loginSuccess:
  layout:  not_logged

profileSuccess:
  stylesheets: [widgets.css, encod.css, jquery-ui-1.7.2.edit.css]
  javascripts: [jquery.ui.all.min.js, widgets.js, catalogue.js]

submitSuccess:
  layout:  not_logged