indexSuccess:
  javascripts: [searchForm.js, pager.js]
newSuccess:
  stylesheets: [widgets.css, encod.css, jquery-ui-1.7.2.edit.css]
  javascripts: [jquery.ui.all.min.js, catalogue_level_edit.js]
editSuccess:
  stylesheets: [widgets.css, encod.css, jquery-ui-1.7.2.edit.css]
  javascripts: [jquery.ui.all.min.js, widgets.js, catalogue.js, catalogue_level_edit.js]
