newSuccess:
  stylesheets: [widgets.css, encod.css]
  javascripts: [jquery.ui.all.min.js]
editSuccess:
  stylesheets: [widgets.css, encod.css]
  javascripts: [jquery.ui.all.min.js, widgets.js, catalogue.js]